package com.pojo;

// Generated Dec 4, 2019 12:00:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String cmobile;
	private Set orders = new HashSet(0);

	public Customer() {
	}

	public Customer(String cname, String cmobile, Set orders) {
		this.cname = cname;
		this.cmobile = cmobile;
		this.orders = orders;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCmobile() {
		return this.cmobile;
	}

	public void setCmobile(String cmobile) {
		this.cmobile = cmobile;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
