package com.pojo;

// Generated Dec 4, 2019 12:00:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer oid;
	private Stock stock;
	private Customer customer;
	private Integer quantity;
	private Double price;
	private Double total;

	public Order() {
	}

	public Order(Stock stock, Customer customer, Integer quantity, Double price, Double total) {
		this.stock = stock;
		this.customer = customer;
		this.quantity = quantity;
		this.price = price;
		this.total = total;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

}
