package com.pojo;

// Generated Dec 4, 2019 12:00:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer sid;
	private Supplier supplier;
	private String mcompany;
	private String mname;
	private String mdescription;
	private Integer quantity;
	private Double price;
	private String mdate;
	private String edate;
	private Set orders = new HashSet(0);

	public Stock() {
	}

	public Stock(Supplier supplier, String mcompany, String mname, String mdescription, Integer quantity, Double price,
			String mdate, String edate, Set orders) {
		this.supplier = supplier;
		this.mcompany = mcompany;
		this.mname = mname;
		this.mdescription = mdescription;
		this.quantity = quantity;
		this.price = price;
		this.mdate = mdate;
		this.edate = edate;
		this.orders = orders;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public String getMcompany() {
		return this.mcompany;
	}

	public void setMcompany(String mcompany) {
		this.mcompany = mcompany;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMdescription() {
		return this.mdescription;
	}

	public void setMdescription(String mdescription) {
		this.mdescription = mdescription;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getMdate() {
		return this.mdate;
	}

	public void setMdate(String mdate) {
		this.mdate = mdate;
	}

	public String getEdate() {
		return this.edate;
	}

	public void setEdate(String edate) {
		this.edate = edate;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
