package com.pojo;

// Generated Dec 4, 2019 12:00:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private Integer supid;
	private String sname;
	private String smobile;
	private String semail;
	private String saddress;
	private Set stocks = new HashSet(0);

	public Supplier() {
	}

	public Supplier(String sname, String smobile, String semail, String saddress, Set stocks) {
		this.sname = sname;
		this.smobile = smobile;
		this.semail = semail;
		this.saddress = saddress;
		this.stocks = stocks;
	}

	public Integer getSupid() {
		return this.supid;
	}

	public void setSupid(Integer supid) {
		this.supid = supid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSmobile() {
		return this.smobile;
	}

	public void setSmobile(String smobile) {
		this.smobile = smobile;
	}

	public String getSemail() {
		return this.semail;
	}

	public void setSemail(String semail) {
		this.semail = semail;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
